### ISSUE TITLE
Add ability to have filters that apply to all configurations

### ISSUE THREAD

**Issue by samaybar** [haganbt/PYLON-exporter#61]
Would be helpful to have a query filter that can apply to all the configs in a config file.

**Comment by haganbt** [comment]
Complete with ffa1bf7bb404ed0c2f04c3121a22276d7b38d306

**Comment by haganbt** [comment]
Leaving this issue open as a reminder that global filter code needs to be refactored for better reuse.

**Comment by haganbt** [comment]
Closing.
