### ISSUE TITLE
Hashtags do not update with Volume Bubble selection in Tableau

### ISSUE THREAD

**Issue by samaybar** [haganbt/PYLON-exporter#63]
Don't know if this is a bug or a feature request, but on the Topics & Hashtags dashboard, clicking on a volume bubble updates the topics for that tag, but not that Hashtags. (It appears the data is set up to support it, but the associated action doesn't seem to exist.)

**Comment by haganbt** [comment]
As discussed, the flow is brand -> topic -> hashtags.

I think renaming "Hashtags" to "Topic Hashtags" is the immediate fix.

**Comment by haganbt** [comment]
Complete @samaybar
