### ISSUE TITLE
Workbook is looking for incorrect file names

### ISSUE THREAD

**Issue by deannomuraatdatasift** [haganbt/PYLON-exporter#68]
Appears that when a config filename has more terms than "standard-tableau", the workbook looks for csv's with filenames that duplicate the last term in the string.  e.g. if the config file is named "standard-tableau-meltwater.js", then the resulting workbook looks for csv's named, "standard-tableau-meltwater-meltwater..."

Confirmed this does not happen if the the default "standard-tableau.js" config file is used. It does happen if the additional term in the filename is even a single character ("standard-tableau-a.js")

![screen shot 2015-11-10 at 10 00 55 am](https://cloud.githubusercontent.com/assets/12463071/11071232/950a7b00-8794-11e5-93eb-e2d7199e0dc8.png)

**Comment by samaybar** [comment]
This looks like the same ting that was happening for me when I was getting
Tableau workbook errors.

**Comment by haganbt** [comment]
Fixed @deannomuraatdatasift @samaybar
